//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Assg_CodeFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_details_Table
    {
        public int StudentId { get; set; }
        public Nullable<int> Percentage { get; set; }
        public string Branch { get; set; }
        public string City { get; set; }
    }
}
