//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Assignment2_Movie
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movietable
    {
        public int movieid { get; set; }
        public string moviename { get; set; }
        public string dateofRelease { get; set; }
    }
}
